ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_secret VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_recovery_codes VARCHAR(4096) NULL;
