CREATE TABLE IF NOT EXISTS organizations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'viewer',
  organization_id INTEGER
);

CREATE TABLE IF NOT EXISTS devices (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  last_seen TIMESTAMP NULL,
  ip VARCHAR(64) NULL,
  version VARCHAR(64) NULL,
  metrics JSON NULL,
  organization_id INTEGER NULL
);

CREATE TABLE IF NOT EXISTS media (
  id SERIAL PRIMARY KEY,
  organization_id INTEGER NULL,
  name VARCHAR(255) NOT NULL,
  path VARCHAR(1024) NOT NULL,
  mime_type VARCHAR(128) NOT NULL,
  thumbnail_path VARCHAR(1024) NULL,
  duration_seconds INTEGER NULL,
  uploaded_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS playlists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS schedules (
  id SERIAL PRIMARY KEY,
  playlist_id INTEGER NOT NULL,
  target VARCHAR(255) NOT NULL,
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS settings (
  id SERIAL PRIMARY KEY,
  key VARCHAR(255) UNIQUE NOT NULL,
  value VARCHAR(4096) NOT NULL
);

CREATE TABLE IF NOT EXISTS device_logs (
  id SERIAL PRIMARY KEY,
  device_id VARCHAR(64) NOT NULL,
  level VARCHAR(32) NOT NULL,
  action VARCHAR(128) NOT NULL,
  message VARCHAR(4096) NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT NOW()
);
